### PR TITLE
Justgar

### PR DESCRIPTION
**Pull request by justgar**
updated this Just IN series readme

### CODE REVIEW

**Review by jimbobbennett — CHANGES_REQUESTED** [review]
Can you remove all locale strings from links to Learn TV, makeCode, garage etc.

Do you have tracking codes for this? If so, can these be added to all Microsoft links.

**Comment by jimbobbennett** [comment]
Would it be beneficial to add any images to this?

What about links to guests as this is an interview show? Should the guests be highlighted on this series page to drive interest from folks interested in a specific guest.

**Comment by justgar** [comment]
Dropped locales. Will add guests and tracking tags at later time. Thanks!

**Comment by jimbobbennett** [comment]
> Dropped locales. Will add guests and tracking tags at later time. Thanks!

Still an en-us on lines 12 and 13

**Comment by justgar** [comment]
fixed en-us

**Review by jimbobbennett — APPROVED** [review]

**Pull request merged**
