### PR TITLE
Bioscience Refresh

### PR DESCRIPTION
**Pull request by dnj55**
Here is the notebook and supporting data for the bioscience refresh on DS1.

### CODE REVIEW

**Comment by dnj55** [comment]
Added additional changes (addressed 4/1/20 feedback) to PR.

**Comment by sguthals** [comment]
@dnj55 - Please see my inline comments to ML1. I put them as "*From Sarah:* throughout.

**Comment by sguthals** [comment]
Hi there, just letting you know that I have updated the targeting branch to `main` since that is now our main branch. There should be no issues with this. 

For future Pull Requests, please make sure you are targeting `main` and make sure you are pulling from `main` to check for compatibility.

**Comment by sguthals** [comment]
Everything looks good. There is one error I'm getting around memory. I have a 64gb ram, so I'm worried others might be getting it? Is this an issue with how memory is handled in Visual Studio code?

**Pull request merged**
