### PR TITLE
Doing a little cleanup

### PR DESCRIPTION
**Pull request by GeekTrainer**

### CODE REVIEW

**Comment by GeekTrainer** [comment]
> Can you include a short sentence why you're deleting all of these files? I trust you, I'd just like to know why before I approve+merge

It's always good to document! :-) I was just getting rid of a folder we're not using. There were two different startersite folders. The one with the dash is the one we should be using.

**Comment by sguthals** [comment]
Shoot, looks like there are conflicts after all. 
@GeekTrainer - can you resolve these conflicts and then I will re-approve?

**Comment by GeekTrainer** [comment]
OK, it looks like it's cleaned up. Thanks for keeping me honest!

**Comment by leestott** [comment]
Merged agreed as startersite was duplicated content

**Comment by leestott** [comment]
Changes look good

**Pull request merged**
