### PR TITLE
DSVM option

### PR DESCRIPTION
**Pull request by GeekTrainer**
- Added instructions to create DSVM
- General updates to incorporate new steps into flow

### CODE REVIEW

**Comment by sguthals** [comment]
Is this something you'd still like reviewed/merged @GeekTrainer ?

**Comment by GeekTrainer** [comment]
If you could give it a look that'd be great! It adds the option for students to use a DSVM on Azure instead.

**Comment by sguthals** [comment]
Happy to (in a bit today)

**Comment by sguthals** [comment]
Hi there, just letting you know that I have updated the targeting branch to `main` since that is now our main branch. There should be no issues with this. 

For future Pull Requests, please make sure you are targeting `main` and make sure you are pulling from `main` to check for compatibility.

**Comment by madebygps** [comment]
Closing, confirmed by Christopher.

**Pull request closed without merging**
