### PR TITLE
Hack Together keynote / PDF version for reference

### PR DESCRIPTION
**Pull request by nitya**
(PPT available on request - size limitations for upload to GitHub

cc @cyz

### CODE REVIEW

**Review by cyz — CHANGES_REQUESTED** [review]
Hi @nitya,
thank you for sending the material. As this repository is a resource for speakers, please consider the following actions:
- Remove the videos from the pptx and in the corresponding slides, leave the indication of the name of the video that must be included
- Create a folder named `video-[sessionname]` to include your videos

Thank you

**Comment by nitya** [comment]
> Hi @nitya, thank you for sending the material. As this repository is a resource for speakers, please consider the following actions:
> 
> * Remove the videos from the pptx and in the corresponding slides, leave the indication of the name of the video that must be included
> * Create a folder named `video-[sessionname]` to include your videos
> 
> Thank you

Hey @cyz - I can just remove the walkthrough segments of the slides if that helps? In that case I may be able to upload the PPTX directly. Re: video-sessionname, I think the video I included at the top was for the live replay from the session (so I embedded link to YouTube but I don't have access to the MP4)

If the above changes are acceptable I can make them and ship an edit

**Comment by nitya** [comment]
@cyz - can you review and close commit?
Was able to add both PPTX and PDF versions by removing embedded videos and reducing image sizes.

**Comment by cyz** [comment]
Hi @nitya, thanks for your updates. I will accept the PR and add some changes to our base to ensure event flow for our community 👍

**Review by cyz — APPROVED** [review]

**Pull request merged**
