### PR TITLE
GitHub/Reactors Folder Restructuring

### PR DESCRIPTION
**Pull request by KimberlyBolton1**
This pull request is for a complete restructuring of the Reactor folder structure

- Why the changes were made: The current folder structure for Online Streams, Workshops, and Learn was incomplete and lacked parity. This structure adds additional folders and files, aligns to current needs, and provides more consistent structuring across the 3 primary delivery types.

- What kind of review you're looking for: Need @sguthals to review new structure, address questions below, and ultimately approve this request.

- Questions/comments for the Reviewer:
•	Online folder has many subfolders and files. I need some guidance to move these into the correct folders.
•	Just a note: The monthly Online themes are listed (“.Net”, “Dev”, “Open Source”, etc), but when you open them, I’ve listed the weekly themes generically while we wait for them to be defined. We can rename the folders at that point.
•	Workshop Instructor Materials folders: We have these folders both at the L3 (ie “DS1”) and the L4 (ie “DS1 Full day”) folder levels. In practice, will both levels contain unique information or should be have only 1 Instructor materials folder for each Workshop (“DS1”, “DS2”), regardless of the length of format?
•	Workshops/DS/DS1: New structure doesn’t allow for a “learn modules” folder. Do we need to keep it here or can we move to the primary “learn” folder?
•	Workshops/ML/ML1 and Workshops/ML/ML2: Same as above on where to place the Learn folder and other files in this folder.
•	Workshops/AI/AI1: There are lots of what look to be content folders here. In what folders do you recommend they be placed?

### CODE REVIEW

**Comment by KimberlyBolton1** [comment]
@sguthals ready for review.

**Comment by meaghanlewis** [comment]
@KimberlyBolton1 thanks for getting these changes up! I know this is for @sguthals, but I wanted to provide a quick tip. For a Pull Request, especially on as large as this one, you should:
- change the title so that it explains the changes being introduced
- provide an overview in the description of what changes you made

That makes it helpful for anyone wanting to review this to be able to quickly read and understand what's going on.

**Comment by KimberlyBolton1** [comment]
Thank you Meaghan, I really appreciate the tips. I will definitely utilize them moving forward.

Thanks,
Kimberly

On May 7, 2020, at 1:30 PM, Meaghan Lewis <notifications@github.com> wrote:

﻿

@KimberlyBolton1<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKimberlyBolton1&data=02%7C01%7Cv-kibolt%40microsoft.com%7Caad48f68070f4d4e326d08d7f2c588e0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637244802528435734&sdata=4DnvdjjXRrWPdqrCTsZZtadiVaqfQOejOw29ZKD3ZQM%3D&reserved=0> thanks for getting these changes up! I know this is for @sguthals<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsguthals&data=02%7C01%7Cv-kibolt%40microsoft.com%7Caad48f68070f4d4e326d08d7f2c588e0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637244802528435734&sdata=cSEKD2n0MCQoSDTopaoXUUQ7SlcwVEirh%2F9XCgRcr5E%3D&reserved=0>, but I wanted to provide a quick tip. For a Pull Request, especially on as large as this one, you should:

  *   change the title so that it explains the changes being introduced
  *   provide an overview in the description of what changes you made

That makes it helpful for anyone wanting to review this to be able to quickly read and understand what's going on.

**Comment by sguthals** [comment]
Hi there, just letting you know that I have updated the targeting branch to `main` since that is now our main branch. There should be no issues with this. 

For future Pull Requests, please make sure you are targeting `main` and make sure you are pulling from `main` to check for compatibility.

**Comment by sguthals** [comment]
I made a lot of these changes in light of a lot of new things that have happened since.

**Pull request closed without merging**
