### PR TITLE
Create markdown-lint.yml

### PR DESCRIPTION
**Pull request by GeekTrainer**
Here goes nothing

### CODE REVIEW

**Comment by sguthals** [comment]
I've just seen this, but it looks old and isn't passing tests. 

Is this still something you want merged or should we close this @GeekTrainer ?

**Comment by GeekTrainer** [comment]
Sorry. This is something I'm playing with. I will block it here and start playing around with it on a fork.

**Comment by sguthals** [comment]
OK :) You can play with it here on this PR, I just wanted to make sure it wasn't something needing review. We could start using some tags to show when we are needing a review vs playing :)

**Comment by GeekTrainer** [comment]
Actually a great idea. Basically this came from the conversation about having some form of linting done for our markdown. I was trying to figure out how to do that with actions, but got distracted by other things.

**Comment by sguthals** [comment]
Hi there, just letting you know that I have updated the targeting branch to `main` since that is now our main branch. There should be no issues with this. 

For future Pull Requests, please make sure you are targeting `main` and make sure you are pulling from `main` to check for compatibility.

**Comment by madebygps** [comment]
Closing since it's marked as do not merge.

**Pull request closed without merging**
